### ISSUE TITLE
Release notes error

### ISSUE THREAD

**Issue by clburlison** [micromdm/scep#1]
Minor tweak to your [pre-release notes](https://github.com/micromdm/scep/releases/tag/v0-dev).

```bash
cd scep/testca
```

should be changed to

```bash
cd scep
```

I would also add a note about downloading the scep binary & making it executable after the git pull. 

Other than that you're right "it works!" :+1:

**Comment by groob** [comment]
Thanks for trying it out! 

I've updated the README and release notes.
