### ISSUE TITLE
use scep with sscep

### ISSUE THREAD

**Issue by kfandhl** [micromdm/scep#100]
I used the micromdm/scep as a server and the sscep as a client. I cannot enroll the certificate. 
root@ubuntu:/home/autotest/workspace/src/github.com/micromdm/scep# ./scepserver -depot depot -port 2016 -challenge=secret -debug -allowrenew 0
level=info ts=2019-01-03T09:03:08.94824173Z caller=scepserver.go:154 transport=http address=:2016 msg=listening
level=info ts=2019-01-03T09:03:28.033250936Z caller=service_logging.go:46 component=scep_service method=PKIOperation err="asn1: structure error: tags don't match (16 vs {class:1 tag:13 length:73 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} contentInfo @2" took=153.472Âµs
level=info ts=2019-01-03T09:03:28.033372091Z caller=endpoint.go:186 op=PKIOperation error=null took=280.669Âµs
level=info ts=2019-01-03T09:03:28.033502567Z caller=logutil.go:70 component=http method=GET status=500 proto=HTTP/1.0 host=127.0.0.1 user_agent= path="/scep?operation=PKIOperation&message=MIIH2gYJKoZIhvcNAQcCoIIHyzCCB8cCAQExDjAMBggqhkiG9w0CBQUAMIIEQQYJ%0AKoZIhvcNAQcBoIIEMgSCBC4wggQqBgkqhkiG9w0BBwOgggQbMIIEFwIBADGCAlIw%0AggJOAgEAMDYwMTELMAkGA1UEBhMCVVMxEDAOBgNVBAoTB3NjZXAtY2ExEDAOBgNV%0ABAsTB1NDRVAgQ0ECAQEwDQYJKoZIhvcNAQEBBQAEggIAwDvarhz04E3qM8FZ7JJl%0Anuu6R%2BAL99Pk75mmkBXx8sU8ydcoc1MAJOLrt2Q7VfcbI1txiFH9iuC3HcI%2BT6pI%0AGo6SoWba6spBOBsvf8GpIOtxoCpg%2BCL%2B4Kcc%2BwvfnE%2BsSKGCZ0Rfcovpv9WUIY3O%0Ay9aawowMrRlc5/os4c5T6%2BChdACYsQu%2BvRkBE/fU0mD8bDbUhznpdkK7oquKvDcN%0AcS3qaeNdnPmf0NBNbns1LyrCu1kIIcefcFTNVmzQuBva9VYyMcq9Z9b0Mk76lH4b%0AU1G56VwWBQuSmtUe0vAiz/VZBcsfB9Uq8X8RoKMJodeS7EHHY/J27T8jHkQ1LkcS%0AKiFByedq5gMG%2BJEJNw7T/vN0mGoYBrihLLhGWOmb/1hY%2BZ%2BavoL8Ew734KaKlAQL%0A0VPsctE1Hv7lrw%2Bf1tLl3rv7AuUSJ1g1SD22C/6zwyo8m2QISDVLYG37kwR4Fq6d%0AtDdCc1HjbXmDmxQgEe94AKqZIcXJEQZB8D%2BMz78u/etlXODoOq5%2B%2BGFwbH3e5cM%2B%0ApZnouOoDBoiSBKblKUzRp3YpE6aofIg/bvJW/3JxT9f3c8Qh5ff%2BdeN%2Biv%2BPsBRf%0Arf/tQ8JKN2J/2qNhsEU/s2R0E1MZNMlgGJEf/3j%2BF3/7Qn1YMsUJIgCgBVxFJrfz%0AsHU0FmHYBrtzmDJui7GeaYswggG6BgkqhkiG9w0BBwEwEQYFKw4DAgcECGJ6I/8z%0Ase2jgIIBmHlCMooWSIH9OyK%2BbmycP7nfmxkWKgWS42ziUftHRwVWdYkCY8sC8UWX%0AnAESzr1CPbSd3tcyJX8mD9lO3dcQKO8IvCG2LDjZQ3O8Lcuuqg5RKlrhe6ZinA3e%0ADnuf9X2uAeu3nFk6dMDedMW8gZCwDpln5NednhHgVlib2JTH1/1UhfhFqWeAoxB9%0AoDR9ywLNVupSXM4gMc7vs5dzrKQ0bK2PxSYmGX7nofOQO0fgH1ghFoXXs7pYrCGV%0AIbkSVsl0dvC7asNodVOZTaexb/l5Pgv51Wf%2BopmKTHcBLoRL5IrWJATzFehNlGDg%0ArJfb5KIA59exW77fFswcQkCBVDVGZ6MBN%2B9dMxBQT0TYCrJxJAg6C7SEBJ1d%2BOpH%0ARrl5OCbPlxmCaxZPuMwIMCcp8vpeDG/vFudbzp5mykOZbNQtk/hsPEhn5XispOKB%0AsLIVDoXSjVI%2BHfR00bZcrPzqdZv4wNsBOR5AS5QWwY7qAZaydHp1aA7AwblZPmkX%0ALaSMcEGS/qngWJwiuVCkVfKY9L1ZqS1xGqfJBKs%2Bc6CCAcEwggG9MIIBJqADAgEC%0AAiBFODdEOEQwM0JFRDAwOTI1MkUyREY0MTIxQjcwNDAwRTANBgkqhkiG9w0BAQQF%0AADAVMRMwEQYDVQQDDAoxNzIuMTcuMC4yMB4XDTE5MDEwMzA5MDMyOFoXDTE5MDEw%0AOTExMDMyOFowFTETMBEGA1UEAwwKMTcyLjE3LjAuMjCBnzANBgkqhkiG9w0BAQEF%0AAAOBjQAwgYkCgYEAy58/yfmv7Hd60QbOwZfy4XZy/IRtLQFxXazor0dp0S10gF6Z%0A2LZSlLgxQ3ift2SbV%2Bch4dunNAzSPVmE/QaapY%2BBUPBuvKoQfSYTwFBxlG2YM0yv%0AV1Q87B3r6X45mYyv6z/uUleimf6rA5k1X7Als1fD31uY8B1JpnvJRDv6ZYsCAwEA%0AATANBgkqhkiG9w0BAQQFAAOBgQCS5RqvK0LHpsF/5RGIyF4varZWbgYUzm6ApL0o%0AbaK/qB%2B6ND2TrjldK15NQZKXfFEwke49ERCY6SrQuOZRy%2BEvrRqsNMzsGX6XEDpe%0AZ6Rc6cDtvm4N8PsrqJzV1sXGsspNDTxdf3MeOgV%2BQndSwOR2XD55oZGss35T3wwQ%0A/SPkPjGCAaYwggGiAgEBMDkwFTETMBEGA1UEAwwKMTcyLjE3LjAuMgIgRTg3RDhE%0AMDNCRUQwMDkyNTJFMkRGNDEyMUI3MDQwMEUwDAYIKoZIhvcNAgUFAKCBwTASBgpg%0AhkgBhvhFAQkCMQQTAjE5MBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZI%0AhvcNAQkFMQ8XDTE5MDEwMzA5MDMyOFowHwYJKoZIhvcNAQkEMRIEEKcBVlQxlxaV%0A8bzQffnlZPwwIAYKYIZIAYb4RQEJBTESBBBkFoZoEAfmzoPeIGqUqvxhMDAGCmCG%0ASAGG%2BEUBCQcxIhMgRTg3RDhEMDNCRUQwMDkyNTJFMkRGNDEyMUI3MDQwMEUwDQYJ%0AKoZIhvcNAQEBBQAEgYB6fCz6AodTiISboDJgd0orslKRVQQRFgQEl32/ioM/hoNb%0AzPucVwKg2TlAudNbUKVPAeY/ak7AVbNpE/vTNCTKaBQEALLSjqyjNGHx8PBGu9ew%0AUGyZi%2BsCZoNQd4Q5IVnkpwL5nzXuQN3D1Fxh1qtPnu5z3EiDJru2EAheA5YKgg%3D%3D%0A"

**Comment by aduez** [comment]
Are you sending a base64 encoded GET request?

**Comment by kfandhl** [comment]
@aduez -Thank you for your comment, I check the sscep code and it sends GET request with base64. Do you mean that the scep server cannot support the GET request with base64?

**Comment by aduez** [comment]
@kfandhl That's indeed the case as of today. I've had the same error than you had and reported the bug here:
https://github.com/micromdm/scep/issues/98
I've come up with a dirty fix that you can apply, but @groob suggested a better solution, if one has time to implement it.

**Comment by jessepeterson** [comment]
GET support added in #114
