### ISSUE TITLE
PAN-OS 9.1 SCEP Configuration

### ISSUE THREAD

**Issue by mrjester888** [micromdm/scep#105]
I am trying to configure a SCEP server for use with Palo Alto Networks GlobalProtect.  

I am running scep on a linux VM.  I have tested with a CA signed intermediate and a SCEP generated CA (scepserver-linux-amd64 ca -init) with the same results. I have modified a few of the PAN-OS configuration items to try to correct the error, but no combination I have found so far seems to work.

./scepserver-linux-amd64 -version
scep - v1.0.0
git revision - a202afd5e358b857c95d048fc47432759db0d9bd

I have tried the debug flag, but it doesn't appear to exist in my version.  What info do you need to help identify the source?

```
ts=2020-05-02T14:00:34.651915342Z caller=service_logging.go:50 component=service method=PKIOperation err="asn1: structure error: tags don't match (16 vs {class:1 tag:13 length:73 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} contentInfo @2" took=58.786µs
asn1: structure error: tags don't match (16 vs {class:1 tag:13 length:73 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} contentInfo @2
```

**Comment by stoodavies** [comment]
After seeing the info that Ghost put in bug #98 I put what is probably the same hack in, which was to put...

```
        newdata, _ := base64.StdEncoding.DecodeString(string(data))
        data=newdata
```

into ParsePKIMessage inside scep/scep.go

However, that isn't sufficient, as PAN-OS is getting a cert, but doesn't like the format of it.   The new error is...

> SSLMGR generate SCEP certificate failed. SCEP:SERVERNAME, Error:Modify request subject (/serialNumber=aa:bb:cc:dd:ee:ff/CN=USER) to cert subject (/CN=USER/serialNumber=aa:bb:cc:dd:ee:ff)

**Comment by jessepeterson** [comment]
So it sounds like the SCEP portion is working (and by the way #98 is closed/merged now). It's just that the issued certificate isn't in a format PAN-OS likes. Is that correct? Any other logs or indicators you can share? Can you contact the vendor to find out more about its requirements?
