### ISSUE TITLE
Certificate Renewals do not do any validation

### ISSUE THREAD

**Issue by directionless** [micromdm/scep#117]
Experimenting with https://github.com/micromdm/scep/pull/115 I noticed that there does not appear to be any kind of verification on a renewal. I tested this by starting two servers using challenge passwords, and then renewing one cert against the other. This succeeds, when obviously it should fail.

Playing with some `printf`, I can see that the renewal gets to [PKIOperation](https://github.com/micromdm/scep/blob/e9687bac0bd7c9ad3d508b070308a9dacefb8f47/server/service.go#L84) where it obviously passes through.

A renewal will not have a challenge, but it _should_ be signed by the existing client cert. So that signature must be verified, all the way back to the CA root. The right place for this _might_ be in [DecryptPKIEnvelope ](https://github.com/micromdm/scep/blob/e9687bac0bd7c9ad3d508b070308a9dacefb8f47/scep/scep.go#L317) but the behavior around verification needs to be different on a `PKCSReq` from a `RenewalReq`

Regardless, https://github.com/micromdm/scep/pull/116 may help. And this needs real test cases.

**Comment by groob** [comment]
This is now fixed.

**Comment by smanneri** [comment]
I am looking for some more information on this to better understand this case. How the existing certificate is used as a trust point for renewal requests I see that the decrypt function is passed with a ca-cert and a ca-private key. Does it do all the work of verification? And which package does it? I thought the existing certificate’s public key was used to decrypt the new CSR. Is it used for something more in this case? like the existing certificate is similar to the challenge password here? Its signature will be verified by the CA’s private key we passed ? That's how it validates the authenticity of the sender? It woulb be great help if i get clarification on these questions.  Thank you .

**Comment by smanneri** [comment]
I am looking for some more information on this to better understand this case. How the existing certificate is used as a trust point for renewal requests I see that the decrypt function is passed with a ca-cert and a ca-private key. Does it do all the work of verification? And which package does it? I thought the existing certificate’s public key was used to decrypt the new CSR. Is it used for something more in this case? like the existing certificate is similar to the challenge password here? Its signature will be verified by the CA’s private key we passed ? That's how it validates the authenticity of the sender. It would be great help if I get clarification on these questions.  Thank you.
