### ISSUE TITLE
Regression in DecryptPKIEnvelope

### ISSUE THREAD

**Issue by fdurand** [micromdm/scep#120]
Hello Guys,

i am using this lib to implement scep on a pki project and i noticed a regression with the DecryptPKIEnvelope function.
It look like since the mozilla pkcs7 has been introduced, it miss some information returned by pkcs7.Parse().

It's easy to test, just run "go test" in the scep directory and you will see that it fail:

```
scep$ go test
--- FAIL: TestDecryptPKIEnvelopeCSR (0.03s)
    scep_test.go:51: invalid data len 0
--- FAIL: TestSignCSR (0.03s)
    scep_test.go:74: invalid data len 0
--- FAIL: TestNewCSRRequest (0.50s)
    scep_test.go:24: pkcs7: signing time "2021-01-21T01:46:12Z" is outside of certificate validity "2016-05-31T11:30:14Z" to "2016-05-31T11:30:14Z"
```

I did a change in the pkcs7 lib to make it work: (https://github.com/inverse-inc/pkcs7/commit/7edd63052124e745b0e842ef21126008f9624c3e)

```
scep$ go test
--- FAIL: TestNewCSRRequest (0.19s)
    scep_test.go:24: pkcs7: signing time "2021-01-21T01:47:49Z" is outside of certificate validity "2016-05-31T11:30:14Z" to "2016-05-31T11:30:14Z"
FAIL
exit status 1
FAIL	github.com/micromdm/scep/scep	0.298s
```

Regards
Fabrice

**Comment by groob** [comment]
I think this is resolved now?

**Comment by fdurand** [comment]
Yes looks to be fixed with https://github.com/micromdm/scep/pull/128
