### ISSUE TITLE
Populate server's CertRep with CA certificates before verifying

### ISSUE THREAD

**Issue by omorsi** [micromdm/scep#122]
The following is stated in [RFC: PKCS #7: Cryptographic Message Syntax Version 1.5: SignedData type](https://tools.ietf.org/html/rfc2315#section-9.1).
> certificates is a set of PKCS #6 extended certificates and X.509 certificates. It is intended that the set be sufficient to contain chains from a recognized "root" or "top-level certification authority" to all of the signers in the signerInfos field. There may be more certificates than necessary, and there may be certificates sufficient to contain chains from two or more independent top-level certification authorities. **There may also be fewer certificates than necessary, if it is expected that those verifying the signatures have an alternate means of obtaining necessary certificates (e.g., from a previous set of certificates).**

IIUC, this means that in SCEP context, it is valid that as a response to PKCSReq message, a SCEP server returns a PKIMessage without adding the CA certificate because there is an alternate means of obtaining necessary certirficates, which is using [GetCaCert](https://tools.ietf.org/html/rfc8894#section-4.2) in this case.

If a SCEP server acted in this valid way, PKCS7 verification will fail in https://github.com/micromdm/scep/blob/f3adbb75202bf4f4f244e05be4f315f708bb75b0/scep/scep.go#L218

The proposal here is not to remove verification, but to populate the certificates field with the CA certificate obtained by the GetCaCert call before verification.

**Comment by pavolmarko** [comment]
I think this sounds reasonable and we've seen a SCEP server behave like this.
Is the proposal to simply add the GetCaCert certs to the list of certs from the SignedData that is going to be verified?

**Comment by groob** [comment]
I think this sounds reasonable as well. If the client knows what to expect it could even be configured with a flag.

**Comment by omorsi** [comment]
> Is the proposal to simply add the GetCaCert certs to the list of certs from the SignedData that is going to be verified?
Yes, exactly.

**Comment by pavolmarko** [comment]
SGTM!
