### ISSUE TITLE
Encode CSRs only with certificates with KeyEncipherment KeyUsage

### ISSUE THREAD

**Issue by omorsi** [micromdm/scep#123]
Currently, the CSR sent in a PKCSReq message is encrypted with all the certificates returned from GetCaCert operation.
https://github.com/micromdm/scep/blob/f3adbb75202bf4f4f244e05be4f315f708bb75b0/scep/scep.go#L448
A windows SCEP server may not just return the CA certificate, but also NDES certificates. Some of these certificates are not created with KeyEncipherment KeyUsage. Some of them are only for Digital Signature purposes. Adding these certificates as recipients for the encrypted messages introduces decryption errors from the server's side.

The proposal here is to filter the certificates received from GetCaCert by KeyUsage, particularly KeyEncipherment, and use only those as the encrypted content recipients.

**Comment by pavolmarko** [comment]
For comparison, jscep has the selection rules here:
https://github.com/jscep/jscep/blob/master/src/main/java/org/jscep/client/inspect/DefaultCertStoreInspector.java#L52

The selection rules as interpreted by me seem to be:
Find the first cert that is an end-entity cert (no "basic constraints" in the cert or marked as non-CA in "basic constraints") and has Key Usage keyEncipherment = true .
If that doesn't yield anything, find the first cert that is an end-entity cert and has Key Usage dataEncipherment = true.


Note that jscep also has similar logic for selecting a "signer" certificate in https://github.com/jscep/jscep/blob/master/src/main/java/org/jscep/client/inspect/DefaultCertStoreInspector.java#L38 . This seems to be doing:
Find the first cert that is an end-entity cert and has Key Usage digitalSignature = true.
Do we need to use such logic here too?

**Comment by groob** [comment]
Let's add a helper that filters the recipients by KeyUsage and only returns the ones which would be able to decrypt. 

I'd also be okay with adding a flag for picking the expected CA fingerprint to work with.
