### ISSUE TITLE
Error on "open depot/<a bunch of escaped characters>.pem: invalid argument"

### ISSUE THREAD

**Issue by xndr** [micromdm/scep#125]
Hi, this is on a new install / new setup, both using a clone of the current project, as well as with the pre-built 1.0.0 release package.

Created new CA:
./scepserver-linux-amd64 ca -init

Launched SCEP server and captured a client trying to send a request:

./scepserver-linux-amd64
level=info ts=2021-02-16T23:57:34.237756462Z caller=scepserver.go:154 transport=http address=:8080 msg=listening
level=info ts=2021-02-16T23:58:07.768758551Z caller=service_logging.go:22 component=scep_service method=GetCACaps err=null took=1.63µs
level=info ts=2021-02-16T23:58:07.768851617Z caller=endpoint.go:186 op=GetCACaps error=null took=98.069µs
level=info ts=2021-02-16T23:58:07.768924411Z caller=logutil.go:70 component=http method=GET status=200 proto=HTTP/1.1 host=192.168.1.14 user_agent="CertificateService/1 CFNetwork/978.5 Darwin/18.7.0 (x86_64)" path="/scep?operation=GetCACaps&message="
level=info ts=2021-02-16T23:58:07.771477116Z caller=service_logging.go:34 component=scep_service method=GetCACert err=null took=940ns
level=info ts=2021-02-16T23:58:07.771571709Z caller=endpoint.go:186 op=GetCACert error=null took=282.1µs
level=info ts=2021-02-16T23:58:07.771618866Z caller=logutil.go:70 component=http method=GET status=200 proto=HTTP/1.1 host=192.168.1.14 user_agent="CertificateService/1 CFNetwork/978.5 Darwin/18.7.0 (x86_64)" path="/scep?operation=GetCACert&message="
level=info ts=2021-02-16T23:58:10.178008515Z caller=service_logging.go:46 component=scep_service method=PKIOperation err="open depot/\ufffd\u0000\ufffd\u0005\u0011\ufffd;\u001c\ufffd\u000b$\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd`\ufffd\ufffd\ufffd\n(\ufffd\ufffd$B\ufffd%Awg\u0016z\ufffd\ufffdq\ufffd8\ufffdeΊ\ufffd\u0001\ufffd\ufffd\ufffdU얳\ufffd\ufffd\ufffd\ufffd!\ufffd\ufffd\ufffd\ufffd\ufffd#}\ufffdѓ9\ufffd\ufffd\ufffT\ufffd\ufffd)\n,j\ufffd\tV\ufffdS3\ufffd;\ufffdM\ufffd\ufffd[m\ufffdl\ufffd\ufffd\ufffd\r\ufffd|\r3\u000b\ufffd\ufffd\u0008\u0001\ufffdb\ufffdWмL\ufffdc\u0017 \ufffdg\u001fG\ufffd\t\ufffd4n\ufffd`T\ufffdZN\u0001\ufffd\u0006E\r\n\u0016Ĭ\ufffd\ufffd\u000e\ufffd\ufffd2Opq\u0007\ufffd\ufffd\u001b8\ufffd\ufffd5\ufffd\u000e%\ufffd:B娡s\ufffd\ufffd\ufffdwi\ufffdk\ufffd\ro\ufffd\ufffdev\ufffd\ufffd\u001bHң50\ufffd\ufffd\ufffd>\u001\ufffd@^\ufffd8i\ufffd\ufffdD/a9X㺗\ufffd\ufffd5\ufffd\ufffd\ufffd\u001d\ufffd[\u001eЇܘC\ufffdh\ufffd\ufffd0\n\ufffd>Zrq\ufffd\ufffdɬ\ufffd\ufffdPtB\ufffd\ufffd\ufffd\u000c/\ufffd\ufffdc\ufffd\u0018\ufffd\ufffd\ufffd8F#\u0000\ufffdQ'\ufffd\ufffd\ufffd\ufffd\ufffdS˦lÕ>\ufffd\ufffde\u001e**\ufffd\ufffd(\ufffd<e\ufffd7\u0006zcp3\ufffd\ufffd\u0013\ufffd\ufffdϮ\ufffd]\ufffd.\u0008\ufffdF\ufffd\ufffd\ufffd\u000f\ufffd!\ufffd`6\u00079\u001dq\ufffd\u001c\u000b$\ufffd\ufffd[\ufffd\ufffd\u0013C\ufffd\u0019\u0003\ufffd\"e\u0000\ufffd#\ufffd\ufffd\ufffd\ufffd,\ufffd\ufffdm`{\ufffd\ufffd/\ufffdO\u0005]\u0003}\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdƸ\ufffd\u0015y\ufffd\ufffd\u0003\ufffd\ufffdp\ufffd\ufffd\ufffd\ufffd\u0015\\\",\u0000G\ufffd}\ufffd^\ufffd\u0015\ufffd\ufffd\ufffdcf\ufffdO\u001bd\ufffd]\u0010\ufffd\ufffdV\ufffd[\ufffd\ufffd\ufffd\ufffd\u0007\ufffd\u0001\ufffddΤ\ufffd\u0003\ufffd\ufffd\ufffd\ufffd\ufffd2$\ufffd\ufffd'.\u0014\u0017\ufffd\ufffd\ufffd9\ufffd\ufffd\ufffd\u0011@=oM0\ufffd\u0000\ufffd\ufffd]\ufffdD\ufffd\ufffd \ufffd[\ufffd\ufffdTq\ufffd\r\ufffd\ufffd\u001e\u0007\u0010\ufffd\ufffdyߴY(\ufffdezC\u001c\u000b8 \r\ufffd\ufffd\ufffdH{\u0019\ufffdE\ufffd\nh\ufffdzSQŷa.2.pem: invalid argument" took=66.24925ms
level=info ts=2021-02-16T23:58:10.178088888Z caller=endpoint.go:186 op=PKIOperation error=null took=66.330463ms
level=info ts=2021-02-16T23:58:10.178119026Z caller=logutil.go:70 component=http method=POST status=500 proto=HTTP/1.1 host=192.168.1.14 user_agent="CertificateService/1 CFNetwork/978.5 Darwin/18.7.0 (x86_64)" path="/scep?operation=PKIOperation"

**Comment by groob** [comment]
The file storage uses the CN from the request as a file name when creating the certificate. Looks like your client is sending some value which makes it hard to interpret/create the necessary file path. 

Can you tell me what the client is (looks like mac or iOS from the user agent) and what the configuration is for requesting a new certificate?

**Comment by xndr** [comment]
Hi,

I am using Profile Manager to create a configuration profile for macOS 10.14 and 10.15 workstations.

Here's the values entered for all the fields on the form:

URL = http://192.168.1.5:8080/scep
Name = blank (field is marked as optional)
Subject / X.500 Name = blank (field is marked as optional)
Subject Alternative Name Type = DNS Name
Subject Alternative Name Value = %HostName% (built-in variable that is replaced by the FQDN of the workstation)
NT Principal Name = blank (field is marked as optional)
Retried = 3
Retry Delay = 10 seconds
Certificate Expiration Notification Threshold = 14 days
Challenge = blank (field is marked as optional, I originally had a challenge but deleted it while troubleshooting this issue)
Key Size = 4096 bits

**Comment by groob** [comment]
1. Can you reproduce this with a static value instead of %HostName%?

**Comment by xndr** [comment]
>     1. Can you reproduce this with a static value instead of %HostName%?

Yes, no matter what I put in the "Subject" field, it produced the same error in the log. However, I did some testing, changing each field one at a time until I got scepserver to accept the transaction, and I found that the issue was the blank/empty "SAN" field that needed to have a value in order for scepserver to accept the request.

See screenshot #1 which shows the macOS profile that was failing, and screenshot #2, ,containing the settings that worked.

Let me know if you would like me to do more tests or more verbose logs to troubleshoot the issue, as I assume you want to fix the code to catch this type of missing input?

![SCEP1](https://user-images.githubusercontent.com/27174230/108459275-30a1c380-722b-11eb-81da-6d807417fb85.JPG)

![SCEP2](https://user-images.githubusercontent.com/27174230/108459296-39929500-722b-11eb-9e40-97abc763673b.JPG)

**Comment by groob** [comment]
That's helpful, but maybe you could share a .mobileconfig file instead of screenshots? 

I have a profile with a blank SAN field here and it does not cause the same issue.

**Comment by groob** [comment]
Also, your screenshots show you changing the "Subject" field, but your message claims the issue is SAN. 
Can you clarify which field you're changing? (really a profile I can reproduce with would be helpful). 

When I said a "static" hostname, i mean a value like "foobar" instead of the %HostName%, since I don't know what your hostname is and wouldn't be able to reproduce an issue.

**Comment by groob** [comment]
deleting the "subject" key from my profile does indeed reproduce this bug.

**Comment by groob** [comment]
Okay I see what is happening. 

If the subject is empty, this helper will try to set the subject to the the cert signature field instead. 
https://github.com/micromdm/scep/blob/6027e7654b23b2168d2aa8b5840fe10f953bc717/depot/signer.go#L86

When combined with the file backend this produces a failure to open the specific path. 

This could be an easy fix, but I worry about breaking anyone using the bolt backend with empty subjects, since bolt likely doesn't care about the file name. We can do something specific to the file depot instead...

**Comment by jessepeterson** [comment]
I can't seem to duplicate this. When I use a profile without a Subject in the plist I get CSR/cert subjects that look like "Subject: CN=ConfigProfileUUID:D21C67F8-16D9-4A51-9232-44189D7902D7" and for newer macOS it takes the `PayloadIdentifier` of the SCEP payload for the CN (I'm actually simulating that behaviour in mdmb here: jessepeterson/mdmb@c0b76fce56).

**Comment by xndr** [comment]
> I can't seem to duplicate this. When I use a profile without a Subject in the plist I get CSR/cert subjects that look like "Subject: CN=ConfigProfileUUID:D21C67F8-16D9-4A51-9232-44189D7902D7" and for newer macOS it takes the `PayloadIdentifier` of the SCEP payload for the CN (I'm actually simulating that behaviour in mdmb here: [jessepeterson/mdmb@c0b76fc](https://github.com/jessepeterson/mdmb/commit/c0b76fce56)).

This was occurring on v1.0.0-48-g860c08c.
