### ISSUE TITLE
PKCSReq (19): pkcs7: No certificate for signer

### ISSUE THREAD

**Issue by macnotes** [micromdm/scep#158]
Thank you. This is a very useful project! Would it be possible to have more verbose logging or a few more notes in readme for common configuration errors? I'm not able to determine what I've done wrong. 

This output indicates "PKCSReq (19): pkcs7: No certificate for signer". 

I'm not sure if this is referring to the "SCEP SIGNER" cert I see in the self.pem file or the certs retrieved via the GetCACerts. Neither of those steps throws an error. 

```$ ./scepclient-darwin-amd64 -version
v1.0.0-93-gc892534

$ ./scepclient-darwin-amd64 -private-key key.pem -server-url=https://scep.my.org/certsrv/mscep/ -ca-fingerprint "ABCD1234 ABCD1234 ABCD1234 ABCD1234" -challenge "ABCD1234ABCD1234" -debug

level=info ts=2021-03-21T17:18:15.617963Z op=GetCACert error=null took=791.354809ms
level=debug ts=2021-03-21T17:18:15.620005Z msg="creating SCEP CSR request" transaction_id="GTMHLiKTm9ti+bGw/B0PYO4SupA=" signer_cn="SCEP SIGNER"
level=info ts=2021-03-21T17:18:15.705067Z op=GetCACaps error=null took=81.984467ms
level=info ts=2021-03-21T17:18:15.793994Z op=PKIOperation error=null took=88.830876ms
parsing pkiMessage response PKCSReq (19): pkcs7: No certificate for signer
```

**Comment by omorsi** [comment]
IIUC, it looks like this connetor is interacting with a Windows Server. Would you please take a look at issue #122 and tell me if that is relevant?

**Comment by macnotes** [comment]
Yes, thank you. I did scan for related issues but didn't pick up on that until you suggested it. Closing as duplicate.

**Comment by jessepeterson** [comment]
@macnotes The other issue is closed. Are you still seeing this problem?
