### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by Loreno10** [micromdm/scep#175]
I'd like to build the binary for ARM (on Raspberry Pi 4). I tried to follow the instructions in the `README.md`, which are:

```md
Clone the repository and get into the source directory: go get github.com/micromdm/scep && cd src/github.com/micromdm/scep
Compile the client and server binaries: make
```

I do not know golang, probably that's why I'm having problems following these 2 steps :|

I did install golang (1.17), and I have GOLANG env set (`$HOME/go`). I did `go get github.com/micromdm/scep`. I learnt that it fetches the code and does `go install` on it in the GOLANG directory. I found some files at `$HOME/go/pkg/mod/github.com/micromdm/scep@v1.0.0`.
Following step 2, I tried to run `make`, but all I'm getting is: `make: *** No targets specified and no makefile found.  Stop.`.

What am I doing wrong?

**Comment by jessepeterson** [comment]
Hmm, yeah. Try this:

```
cd ~/go
mkdir -p src/github.com/micromdm
cd src/github.com/micromdm
cd scep
make
```

Maybe our docs need an adjustment..

**Comment by Loreno10** [comment]
Before running `make`, I modified `Makefile` as follows:

```
VERSION=$(shell git describe --tags --always --dirty)
LDFLAGS=-ldflags "-X main.version=$(VERSION)"
OSARCH=$(shell go env GOHOSTOS)-$(shell go env GOHOSTARCH)

SCEPCLIENT=\
        scepclient-linux-arm \
        scepclient-darwin-amd64 \
        scepclient-freebsd-amd64 \
        scepclient-windows-amd64.exe

SCEPSERVER=\
        scepserver-linux-arm \
        scepserver-darwin-amd64 \
        scepserver-freebsd-amd64 \
        scepserver-windows-amd64.exe
```

Basically, I changed `scepclient-linux-amd64` to `scepclient-linux-arm` (and analogical change for the server, although in my case I need just client).
Here's what I see when I run `make`:

```
pi@rpi:~/go/src/github.com/micromdm/scep $ make
GOOS=linux GOARCH=arm go build -ldflags "-X main.version=v2.1.0-dirty" -o scepclient-linux-arm ./cmd/scepclient
go: github.com/boltdb/bolt@v1.3.1: Get "https://proxy.golang.org/github.com/boltdb/bolt/@v/v1.3.1.mod": x509: certificate signed by unknown authority
go: downloading github.com/go-kit/kit v0.4.0
go: downloading github.com/pkg/errors v0.8.0
go: downloading go.mozilla.org/pkcs7 v0.0.0-20210730143726-725912489c62
go: downloading github.com/gorilla/mux v1.4.0
go: downloading github.com/groob/finalizer v0.0.0-20170707115354-4c2ed49aabda
go: github.com/boltdb/bolt@v1.3.1: Get "https://proxy.golang.org/github.com/boltdb/bolt/@v/v1.3.1.mod": x509: certificate signed by unknown authority
make: *** [Makefile:22: scepclient-linux-arm] Error 1
```

How can I fix it?

**Comment by Loreno10** [comment]
Ignore my last post, that was caused by my network setup. When I switched to a "normal" network without any proxies, it worked.

@jessepeterson Yes, I think it makes sense to update the README. People who use golang probably don't need it, but for all the rest, it will be really helpful.

**Comment by jessepeterson** [comment]
@Loreno10 feel free to submit a PR adding the linux ARM target to the Makefile, too :)
