### ISSUE TITLE
Revocation Endpoint

### ISSUE THREAD

**Issue by pagey101** [micromdm/scep#192]
Hi

Kudos on the project. Is there an endpoint to revoke certificates?

I can see the logic is already there for renewals but I would like to be able to manually revoke a certificate.

Thanks

**Comment by jessepeterson** [comment]
There is no actual revocation support at this time, no. Even if there were there's no implemented way to export revocation status from the CA (i.e. CRLs or OCSP). See #53 and #35.

**Comment by pagey101** [comment]
Thanks for the quick reply. That's fine, I read the SCEP spec and found that a SCEP server should not implement a revoke endpoint.

I can do the revocation and CRL generation using openssl and the index.txt database, which is handy.
