### ISSUE TITLE
Is it possible to configure SCEP to get certificate from Let's Encrypt?

### ISSUE THREAD

**Issue by kasi1999999** [micromdm/scep#203]
Hello SCEP team,
is it possible to configure scep utility to act as a CA proxy - my router would be configured to use scep server for issue certificate, then the scep server would use ACME to forward it to Lets Encrypt. If it is possible, can you please provide working sample configuration? Thanks.
Stefan

**Comment by jessepeterson** [comment]
SCEP as a proxy (sometimes called RA I think) to another CA is definitely possible and I don't know of anything that would prevent a proxy or translation to ACME. That said: there's no code built-in to do any of this. If you're willing to write code take a look at the SignCSR interface:

https://github.com/micromdm/scep/blob/699e8df4494ae17445464d664e3856fdecbc01c0/server/csrsigner.go#L11-L17

**Comment by jessepeterson** [comment]
Oh one other note: Let's Encrypt uses different types of challenges. Getting the SCEP to ACME translation working would require handling those challenges on behalf of the SCEP client. _Seems_ doable but that's another element you'd have to figure out.
