### ISSUE TITLE
Implementing PKCS11

### ISSUE THREAD

**Issue by spbkaizo** [micromdm/scep#214]
Hi,

Can you please provide guidelines and an example of how you may add a new provider to Depot?  

I'm trying to extend scepserver so it can be using AWS KMS RSA keys, via PKCS11.

Before I go too far down this attempt, what would you recommend be the implementation approach?

**Comment by jessepeterson** [comment]
I'm gonna close this issue as it's more of a discussion type thing. Feel free to join is the `#micromdm` channel on the [MacAdmins Slack](https://www.macadmins.org) to discuss, though!
