### ISSUE TITLE
can't use static challenge via config profile

### ISSUE THREAD

**Issue by scheblein** [micromdm/scep#22]
I'm able to set a challenge phrase for scepserver and request a cert using scepclient with that challenge phrase. However I'm not able to use that challenge phrase to request a cert via config profile. What am I missing? When not using a challenge phrase, the config profile method works fine.

**Comment by jessepeterson** [comment]
Are you seeing any errors? What behavior are you seeing on the device? Do you have any logs or output you can share? Thanks!

**Comment by groob** [comment]
Related: #44 

I have a solution, will close this when I fix over the next few days.
