### ISSUE TITLE
GetCACert and GetCACap message request and response is OK even if CA is down.

### ISSUE THREAD

**Issue by mini04** [micromdm/scep#31]
Hi,

If ADCS service is stooped or CA is down, then GetCACert and GetCACap request is completed and response is OK. How is it possible??

Thanks,
Mini

**Comment by groob** [comment]
is this using `scepclient`? Please provide more info about your setup. 

On windows SCEP uses NDES not ADCS afaik.

**Comment by mini04** [comment]
I have installed ADCS and NDES in same machine (Window Server 2012 R2), so if I stop the ADCS then NDES will automatically stop.

**Comment by groob** [comment]
Any logs you could provide? 

I'll be honest, even though there's been some interest in having the client work with NDES/Windows Server, I have not resolved many of the issues necessary to do so. Windows NDES is obscure and not necessary in my infrastructure. Having said that, I'd be happy to fix anything that comes up if I can get a bug report with relevant data.

**Comment by mini04** [comment]
Ok let me explain what is the problem. My problem is that when ADCS is stopped then ideally I should not be able to download the CA certificate. So I debug my code and found that GetCACert is still responding if CA service is stopped.
The command is:
http://server_name/CertSrv/mscep/mscep.dll?operation=GetCACert&message=ManagementCA

and for reply from server I am attaching the image:
![a](https://cloud.githubusercontent.com/assets/26891734/24647225/b1bdcfaa-193c-11e7-92ab-4763af4e95e5.png)

and also I am not able to see any log for this command in event viewer.
But when I use PKIOperation command and ADCS is stopped, the command do not get succedded and response failed ( which should be the ideal response if I am correct) and in event viewer , I am attaching the image for that:
![b](https://cloud.githubusercontent.com/assets/26891734/24647657/6e5cfafe-193e-11e7-9f21-c61a7dba0a4b.png)
