### ISSUE TITLE
API for verifying a certificate was signed by this CA

### ISSUE THREAD

**Issue by jessepeterson** [micromdm/scep#32]
You can retrieve the CA's certificate and check the signature and/or Verify the chain _manually_ but it would be nice if we had an API to do this. Perhaps a `Verify` method that checks that the cert is valid (not revoked?)  and that it was generated by this CA. I know this is typically the duty of a "proper" Certificate Authority system but since `micromdm/scep` also implements a de facto CA (via the depots) it ought to support this.

**Comment by groob** [comment]
Tracking in #53
