### ISSUE TITLE
CRL Support

### ISSUE THREAD

**Issue by rbuzzell** [micromdm/scep#35]
Hello,

It would be very helpful if there was some CRL support in this project to revoke certificates of lost or compromised client machines. Does this currently exist in the project or on the road map?

I understand there are some [concerns with CRLs](https://www.imperialviolet.org/2014/04/19/revchecking.html) for server certificates, but I'm not sure if the concerns apply for client certificates where only the issuer (and the services of the issuer) need to check the list.

**Comment by groob** [comment]
I think we can definitely add a static CRL file which is checked by the CA. 

The file format for the default backend already supports a CRL https://github.com/micromdm/scep/issues/7

I'll look into adding support for reading that CRL and a subcommand to revoke a certificate.

**Comment by groob** [comment]
Tracking in #53
