### ISSUE TITLE
unique challenge passwords

### ISSUE THREAD

**Issue by groob** [micromdm/scep#4]
Having a global PSK is problematic. 

Address this by allowing unique PSK for each device. 
- allow an external `-verify /path/to/script` parameter to provide pluggable verification: a user would provide their own validation logic. 
- support some build it validation middleware. 

https://blog.opentrust.com/?p=312

**Comment by np5** [comment]
This is a very useful and necessary feature indeed. The information to pass to the script or middleware would be the requested Subject Name and the challenge. The answer would be the approved Subject Name or an error message. A simple verification middleware over HTTPS could be a first step.
