### ISSUE TITLE
asn1: structure error: tags don't match

### ISSUE THREAD

**Issue by FreshXOpenSource** [micromdm/scep#6]
$ ./scepserver-linux-amd64 -depot depot -port 2016 -challenge=testMDM
$ ./scepclient-linux-amd64 -private-key client.key -server-url=http://127.0.0.1:2016 -challenge=testMDM
asn1: structure error: tags don't match (16 vs {class:0 tag:20 length:48 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} certificate @2

strace reveals : 

[pid 14335] write(3, "GET /?operation=GetCACert HTTP/1.1\r\nHost: 127.0.0.1:2016\r\nUser-Agent: Go-http-client/1.1\r\nAccept-Encoding: gzip\r\n\r\n", 136) = 136
[pid 14335] read(3, "HTTP/1.1 404 Not Found\r\nContent-Type: text/plain; charset=utf-8\r\nX-Content-Type-Options: nosniff\r\nDate: Wed, 07 Sep 2016 15:23:26 GMT\r\nContent-Length: 19\r\n\r\n404 page not found\n", 4096) = 176

**Comment by groob** [comment]
I think it's because you're setting the server-url flag to http://its-lcs-dogtag01.its.unibas.ch:2016 
The client expects the path as well. Try using `http://its-lcs-dogtag01.its.unibas.ch:2016/scep` as the server url.

**Comment by FreshXOpenSource** [comment]
would you mind reseting the hostname from *.unibas.ch to 127.0.0.1 for security reasons?

**Comment by groob** [comment]
Done, 

Should I consider this issue resolved?

**Comment by FreshXOpenSource** [comment]
Using the micromdm client yes. If we try to run sscep against the server and get the same problem. Do you have an idea?

$ 
$ sscep enroll -u http://127.0.0.1:2016/scep -c ca.crt -k local.key -r local.csr -l local.crt -v

sscep: starting sscep, version 0.6.1
sscep: new transaction
sscep: transaction id: D41D8CD98F00B204E9800998ECF8427E
sscep: hostname: 127.0.0.1
sscep: directory: scep
sscep: port: 2016
sscep:  Read request with transaction id: 816360FFEF5C929C55CF29E46C297338
sscep: generating selfsigned certificate
sscep: SCEP_OPERATION_ENROLL
sscep: sending certificate request
sscep: creating inner PKCS#7
sscep: inner PKCS#7 in mem BIO
sscep: request data dump
-----BEGIN CERTIFICATE REQUEST-----
MIIBejCB5AIBADAWMRQwEgYDVQQDDAsxOTIuMTY4LjEuMTCBnzANBgkqhkiG9w0B
AQEFAAOBjQAwgYkCgYEAmbQMeOZ1aJkeRpzGuPsyJw0UkQaEjQ1Xh4rpiVQL6Srz
OJeX8XItdQfULtqppp6o5bUh+PJGqzFpSJAox/skrvVXTY2nqCrTToQ6CngUaDqL
l6FWCmOwyQkuxq5h/MWp3+b2oHwULwggk1ht/mLf0fjEsAzSygI98u2gG2VsbhcC
AwEAAaAlMCMGCSqGSIb3DQEJDjEWMBQwEgYDVR0RAQH/BAgwBocEwKgBATANBgkq
hkiG9w0BAQsFAAOBgQB3e6MalyE6b2SmKjSmVa781QZ7LUd+ei7AJ8ITsSefXLpK
es6tkTWpayolSRqXOOmIQQIOAdBM0xFMBZNT1T4X5lZJ/bfBdhU1jW+gqLdieOLi
rsokpuxVLkuWQiuX79u1SstAO0vtIFpavglSdg/Ofn1pos/WocxyI3RLgUjPOw==
-----END CERTIFICATE REQUEST-----
sscep: data payload size: 382 bytes
sscep: successfully encrypted payload
sscep: envelope size: 1046 bytes
sscep: creating outer PKCS#7
sscep: signature added successfully
sscep: adding signed attributes
sscep: adding string attribute transId
sscep: adding string attribute messageType
sscep: adding octet attribute senderNonce
sscep: PKCS#7 data written successfully
sscep: applying base64 encoding
sscep: base64 encoded payload size: 2702 bytes
sscep: server returned status code 500
sscep: mime_err: HTTP/1.0 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Mon, 12 Sep 2016 13:53:14 GMT
Content-Length: 244

Encode: asn1: structure error: tags don't match (16 vs {class:1 tag:13 length:73 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} contentInfo @2

sscep: wrong (or missing) MIME content type
sscep: error while sending message

**Comment by groob** [comment]
I'll have to play around with `sscep` myself to see what's going on. 
So far I've only tested this project with Apple's SCEP enrollment via profile, but there are numerous versions of the SCEP protocol. 

I suspect the `sscep` server is sending a GET request with a base64 encoded body instead of a POST, which is the more modern variation.

**Comment by FreshXOpenSource** [comment]
sscep uses GET :

# strace -f -s 1400 ./sscep ....
...
sendto(3, "GET /scep?operation=PKIOperation&message=MIIH3QYJKoZIhvc
...

**Comment by groob** [comment]
OK, I'll add that. We ran into a related issue with NDES in #5 

I have an ongoing branch which implements GET requests https://github.com/micromdm/scep/tree/getop would you mind testing that branch?

**Comment by FreshXOpenSource** [comment]
trying to install from source like this :

$ export GOPATH=`pwd`
$ go get github.com/micromdm/micromdm
$ glide install
$ cd src/github.com/micromdm/micromdm
$ go build

gives me the following error :

# github.com/fullsailor/pkcs7
../../fullsailor/pkcs7/pkcs7.go:802: undefined: asn1.TagSequence
# github.com/micromdm/micromdm/management
management/service.go:73: cannot use p (type payload.MDM) as type []byte in argument to svc.pushsvc.Push

I run Go v1.5.3, glide v0.8.3

**Comment by angelsuero** [comment]
Any update about this bug?
Thank you.

**Comment by crazed** [comment]
I just ran into this as well using the latest release.

**Comment by groob** [comment]
@crazed did you add `/scep` at the end of the serverURL?

**Comment by crazed** [comment]
```
# Server run
./scepserver-linux-amd64 -challenge=secret -port=8080

# Client run
./build/scepclient-linux-amd64 -challenge=secret  -server-url=http://10.10.0.5:8080/scep -private-key client.key
Server reply : asn1: structure error: tags don't match (19 vs {class:1 tag:19 length:101 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} string @
```

There is a /scep at the end, also tried /scep/ but it results in the same output.

**Comment by groob** [comment]
This should print a more helpful error now. The usual cause for this error is because the server returns a message which is not a pkcs7 envelope, but the client tries to parse it. 

#43 should have addressed this.

**Comment by msva** [comment]
@groob and what about realisation of getting the cert via GET request (to be compatible with other client software, but not only with `scepclient` from this repo?

**Comment by groob** [comment]
@msva can you open a separate issue describing your usecase?

**Comment by joewarrenmeeks** [comment]
Thread necro:

If you run this without -challenge set on both client and server, then this works.
