### ISSUE TITLE
Refactor server & client out of this repository

### ISSUE THREAD

**Issue by kenkouot** [micromdm/scep#61]
Thanks for the great work on this package! I'd like to suggest either moving the `scep` package to it's own repo or moving the server, client and cmd packages out of this one. The main motivations for this are:

* reduce code footprint for code & security audit purposes
* enforce strong separation of concerns between `scep` package primitives and their consumers

**Comment by jessepeterson** [comment]
Hi @kenkouot. FYI the `scep` package was moved over in #233.
