### ISSUE TITLE
CSR verification callback

### ISSUE THREAD

**Issue by np5** [micromdm/scep#64]
This feature would allow to pass the full CSR to modules for verification before signing.

The modules would be able to not only verify the challenges, like it is already possible with the challenge stores, but could check the CN, or some other attributes of the signing request.

One module could implement the [policy based autosigning scheme of puppet](https://puppet.com/docs/puppet/5.3/ssl_autosign.html#policy-based-autosigning).

**Comment by groob** [comment]
How about 

```
type CSRVerifier interface {
 func Verify(data []byte) (bool, error)
}
```

And the data passed in could be either the csr or challenge?
