### ISSUE TITLE
CA init from Docker produces blank files

### ISSUE THREAD

**Issue by Beanow** [micromdm/scep#71]
Running the readme example to set up a CA in Docker produces blank files for the key and pem.
`docker run -it --rm -v /path/to/ca/folder:/depot micromdm/scep ./scep ca -init`

Running the v1.0.0 linux amd64 build locally on Ubuntu produces new keys.

**Comment by groob** [comment]
Please check that the permissions in your mounted directory are writable.

```
$ mkdir -p scep_depot
$ docker run -it --rm -v $(pwd)/scep_depot:/depot micromdm/scep ./scep ca -init

$ tree scep_depot
scep_depot
├── ca.key
└── ca.pem

```

**Comment by Beanow** [comment]
Oops, false alarm. Of course the new files are owned by root. :no_entry:
Unprivileged sublime text silently opens the files as blank ones when it has no read access.

```
$ docker run -it --rm -v $(pwd)/depot:/depot micromdm/scep sh -c "\
	rm /depot/* && \
	./scep ca -init && \
	cat /depot/ca.pem"

Initializing new CA
-----BEGIN CERTIFICATE-----
MIIFHzCCAwegAwIBAgIBATANBgkqhkiG9w0BAQsFADAxMQswCQYDVQQGEwJVUzEQ
...
7ZJxOz2jYBluO3nC5ODqGlg9pg==
-----END CERTIFICATE-----
```
