### ISSUE TITLE
setting x509.KeyUsageCertSign | x509.KeyUsageCRLSign on the CA certificate breaks macOS

### ISSUE THREAD

**Issue by groob** [micromdm/scep#81]
https://github.com/micromdm/scep/blob/cced6af4d385f2129bc9d6f0969293dba542f668/cmd/scepserver/scepserver.go#L249-L250

Broken in 10.13.4 beta

**Comment by xman1979** [comment]
Could you describe more? I see following error message in scep enrollment without "x509.KeyUsageCRLSign "  10.13.4 beta (17E170c).

CertificateService Server capabilities lack support for 3DES but we're going to use it anyway
CertificateService Creating inner envelope for CSR failed: -50
CertificateService [ERROR] <: [MDM_SCEP_Enroll] Calling SCEPRequestCertSignatureWithCSR -->  <NSOSStatusErrorDomain:-50>
mdmclient [ERROR] <<<<< PlugIn: InstallPayload [CertificateService] Error: Error Domain=NSOSStatusErrorDomain Code=-50 "paramErr: error in user parameter list" UserInfo={IsInternalError=true} <<<<<

**Comment by jessepeterson** [comment]
Tested on 10.13.6 successfully — profile issued and installed successfully. CA cert:

```sh
$ curl -s 'http://scepserver/scep?operation=GetCACert' | openssl x509 -inform DER -noout -text | grep CRL
                Certificate Sign, CRL Sign
```
