### ISSUE TITLE
Change in dependency fullsailor/pkcs7 causing fail

### ISSUE THREAD

**Issue by mamhaidly** [micromdm/scep#85]
I am trying to use the scep library in my Go with Gin Framework server. The deployment to Heroku failed with the following errors:
- scep.go:318:17: p7.EncryptionAlgorithm undefined (type *pkcs7.PKCS7 has no field or method EncryptionAlgorithm)
- scep.go:449:26: too many arguments in call to pkcs7.Encrypt
- scep.go:449:53: undefined: pkcs7.WithEncryptionAlgorithm
- scep.go:542:26: too many arguments in call to pkcs7.Encrypt
- scep.go:542:54: undefined: pkcs7.WithEncryptionAlgorithm

After following the errors, I found out it is related to "github.com/fullsailor/pkcs7" repo.

**Comment by groob** [comment]
You need to use the forked version of pkcs7, and specify the correct source with your dependency management tool. [dep](https://github.com/golang/dep) does this well. 

See an example in the `Gopkg.toml` file:

```
[[constraint]]
  branch = "sha256"
  name = "github.com/fullsailor/pkcs7"
  source = "github.com/groob/pkcs7"
```

**Comment by mamhaidly** [comment]
I tried using the forked repo but I could not. This time, the error is linked to govendor (the dependency management tool I am using, I reported an issue on their repo) so I will close thie one. 
Thank you @groob

**Comment by mamhaidly** [comment]
Did you change anything @groob ? I changed to dep and it automatically downloaded your repo. Is it normal behavior?

**Comment by groob** [comment]
It's specified in the lock file. I did not change anything.

**Comment by mamhaidly** [comment]
Sorry for bothering but I am stuck. 
This is in my Gopkg.lock file
[[projects]]
  name = "github.com/micromdm/scep"
  packages = [
    "scep",
    "scep/internal/pkcs7"
  ]
  revision = "a202afd5e358b857c95d048fc47432759db0d9bd"
  version = "v1.0.0"
and the files that are in it are different than your pkcs7 repo.
Are these the correct files to have pkcs7 running?
I am asking because I am getting an error from a function call in this library while processing the post request made by the built in iOS SCEP client while trying to install a configuration profile.

**Comment by groob** [comment]
What does your Gopkg.toml look like?

**Comment by mamhaidly** [comment]
[[constraint]]
  branch = "master"
  name = "github.com/DHowett/go-plist"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/user/golang-gin"
  go-version = "1.10.2"
  install = [ "./..." ]

**Comment by groob** [comment]
See https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md for how to specify custom sources for packages. You need to specifically specify the pkcs7 dependency. 

The Gopkg.toml file in this repo already does that.
