### ISSUE TITLE
ParsePKIMessage error when parsing POST Request made by iOS SCEP client

### ISSUE THREAD

**Issue by mamhaidly** [micromdm/scep#86]
I have an iPhone installing a configuration profile from my Golang server hosted on heroku.
In the configuration profile, a URL is specified, the iOS SCEP client is supposed to POST the device's info to this URL.
I included the scep library example in README file. The ParsePKIMessage is failing with this error: "pkcs7: attribute type not in attributes".
The POST Request's body has a plist file in it and some unclear characters.

**Comment by groob** [comment]
can you provide something reproducible? Your profile and relevant server code(that compiles)?

**Comment by groob** [comment]
I created https://github.com/groob/mac-scep-playground for testing SCEP profiles. if you could reproduce with that code as a starting point I'd appreciate it.

**Comment by mamhaidly** [comment]
I ll try to reproduce with your repo, later on. For now, I can provide you the configuration profile: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>PayloadContent</key>
    <dict>
        <key>URL</key>
        <string>http://random-heroku-app-name.herokuapp.com/api/postmobileinfoscep</string>
    <key>DeviceAttributes</key>
    <array>
        <string>UDID</string>
        <string>DEVICE_NAME</string>
        <string>VERSION</string>
        <string>PRODUCT</string>
        <string>MAC_ADDRESS_EN0</string>
        <string>IMEI</string>
        <string>ICCID</string>
    </array>
   
    </dict>
        <key>PayloadOrganization</key>
        <string>Example Inc.</string>
        <key>PayloadDisplayName</key>
        <string>Profile Service</string>
        <key>PayloadVersion</key>
        <integer>1</integer>
        <key>PayloadUUID</key>
        <string>fdb376e5-b5bb-4d8c-829e-e90865f990c9</string>
        <key>PayloadIdentifier</key>
        <string>com.example.mobileconfig.profile-service</string>
        <key>PayloadDescription</key>
        <string>Enter device into the Example Inc encrypted profile service</string>
        <key>PayloadType</key>
        <string>Profile Service</string>
    </dict>
</plist>
and here is the function handling the url in the configuration profile ( I am using gin framework too):

// PostMobileInfoSCEP replies to the iOS Client
func PostMobileInfoSCEP(c *gin.Context) {
	body, err4 := ioutil.ReadAll(c.Request.Body)
	if err4 != nil {
		log.Println(err4)
	}
	log.Println(string(body[:]))
	// parse the SCEP message
	msg, err5 := scep.ParsePKIMessage(body)
	if err5 != nil {
		// handle err
		log.Println(err5)
	}

	// do something with msg
	log.Println("Message type: " + msg.MessageType)
}

**Comment by mamhaidly** [comment]
and here is the POST Request I am receiving from the iOS SCEP Client:
![screenshot_2018-06-06_18-41-15](https://user-images.githubusercontent.com/24892806/41049293-4356f46e-69b9-11e8-98f4-2e6f65da77ea.png)

**Comment by jessepeterson** [comment]
@mamhaidly it looks like you're doing OTA enrollment here. There's a two-step process with this. I would honestly ditch that for the moment and instead first try to get a normal SCEP profile working, then work on OTA enrollment which has a confusing two-step process. MicroMDM implements OTA enrollment file (and on iOS) so we know this works, I'm guessing there's some separate steps that aren't working for you.

It sort of sounds like you're pointing the OTA Phase 2 response at the SCEP server? Which isn't going to work, you'll need to delivery another configuration profile with a SCEP payload to get that working.

**Comment by mamhaidly** [comment]
@jessepeterson that is exactly what I am trying to do. It is not an issue with your code. Thank you for your support. I will close this issue.
