### ISSUE TITLE
Im getting some errors using a device client

### ISSUE THREAD

**Issue by 000amorfo** [micromdm/scep#88]
Im setting up a mdm server and I want to use the scep of micromdm. I create the ca.ca and the ca.pem and then run both servers (mdmserver and scepserver)
when the device tries to ask for the certificate its appearing a box " The SCEP server returned an invalid response" 
this is showed in the scep console
![mdm3](https://user-images.githubusercontent.com/36115136/41500856-07363830-719a-11e8-8990-59e0216d6bb4.png)

any idea abt it?
lots of thanks

**Comment by jessepeterson** [comment]
The SCEP server has been used for MDM for some time now successfully; and this issue is really old. Feel free to re-open and add any details (i.e. the Apple SCEP profile) if it doesn't work against current code.
