### ISSUE TITLE
what is the default password of the ca.key?

### ISSUE THREAD

**Issue by FreshXOpenSource** [micromdm/scep#9]
$ ./scepserver-darwin-amd64 ca -init
Initializing new CA
$ openssl rsa -in depot/ca.key -out depot/ca-new.key
Enter pass phrase for depot/ca.key:

scepserver.go sets a default of "" which seems to lead to this undefined behaviour

**Comment by groob** [comment]
What kind of undefined behavior?

**Comment by FreshXOpenSource** [comment]
the CA should have no password if not defined

**Comment by groob** [comment]
This bit here https://github.com/micromdm/scep/blob/864b3e4b501f53b4897bdbde36e4960ba04f8bcf/depot/file/depot.go#L372-L376 should be wrapped in an `if password != ""` statement. 

Do you want to submit a patch?
