### ISSUE TITLE
Server Without Go Kit

### ISSUE THREAD

**Issue by oscartbeaumont** [micromdm/scep#94]
Hello,
I am trying to get a SCEP server working without the use of Go Kit. I have tried to make it work using the code linked [here](https://gist.github.com/oscartbeaumont/95e7982d0d41d21666a3326f6f80e06b) but it is not working. Is there an example that exists for doing this? I have tried to make it work by using the code in the README.md but have had a problem with the variable `csr.Subject` (Sent From The Client in The PKIOperation) being blank and so the device (An Apple Mac With a SCEP Profile) is rejecting the returned cert for not matching the CommonName (At least that is what I think the problem is).

**Comment by groob** [comment]
Can you explain what you mean by "trying to use the server without go-kit? Go Kit is just a set of HTTP libraries we use to create the handlers. 

I'm also not sure what that has to do with the rest of the question. How is the CSR related? 

If you can provide a few examples, I might be able to better answer your questions. 
The gist you linked is too long.

**Comment by groob** [comment]
All the business logic is implemented on the `service` struct here https://github.com/micromdm/scep/blob/a136542b4bc9312ba88f1beaf1369d67bc744614/server/service.go#L84

After you decode the request you need to either reuse it, or implement it in your own code.

**Comment by oscartbeaumont** [comment]
Sorry, the question and the demo code were confusing. I managed to get it working using the logic implemented on the `service` struct like you said.
Thanks for the help.
